Style fixes to abmFormMascota, QoL changes and better handling of png files
mateoregodesebes/Pagina-Veterinaria pull request #12
Opened 2024-07-12 03:30 UTC by JosepSoc

Cambios generales en los commits.

Cosas que habria que hacer:
-Cuando eliminas una mascota de la bd se tendria que borrar la imagen del mismo
--Problema de implementacion: manera en la que se guardan las imagenes ahora, 
--se tendria que hacer una carpeta de imagenes por cliente maybe, porque si 2 suben
--una imagen con el mismo nombre se pisan (otro problema potencial actual)

-Poner un limite a la imagen que se sube, ya sea de mb o de resolucion, ahora te podrian
colapsar la bd a subir imagenes pedorras de muchos gb calculo. Ademas de que se romperia la imagen preview

-Mejorar la manera que se encuentra o muestra la imagen preview, esta muy rustico

2024-07-12 22:39 UTC, mateoregodesebes commented
# Review
## CRUD de mascotas
Lo unico que no sé por qué esta es el `style="margin-left: 35%;"`. No sé si es que se ve más centrado asi en tu pantalla o algo
![image](https://github.com/user-attachments/assets/d00e8d09-1c6b-44cc-beba-6b200b82d11c)
Si se lo saco ahi me queda bien centrado a mi:
![image](https://github.com/user-attachments/assets/e7fdc420-1a37-4308-b5e7-eefbc6d97454)

El CRUD de mascotas anda bien salvo el delete. Por alguna razón el delete, borrar cualquier mascota ocasiona que se borre la mascota que figura con el _menor id_. 
Despues en el resto de cosas anda bien.

## CRUD de clientes
Funciona todo bien excepto lo del delete que, al borrar cualquier cliente, borra al de _menor id_.

---
Corregi esas cositas y estaría. Me parecería correcto si las cosas que mencionaste las elevamos como issue asi si las tenemos pendientes y se las podemos preguntar a algun profesor o algo

2024-07-12 22:40 UTC, mateoregodesebes requested changes
# Review
## CRUD de mascotas
Lo unico que no sé por qué esta es el `style="margin-left: 35%;"`. No sé si es que se ve más centrado asi en tu pantalla o algo
![image](https://github.com/user-attachments/assets/d00e8d09-1c6b-44cc-beba-6b200b82d11c)
Si se lo saco ahi me queda bien centrado a mi:
![image](https://github.com/user-attachments/assets/e7fdc420-1a37-4308-b5e7-eefbc6d97454)

El CRUD de mascotas anda bien salvo el delete. Por alguna razón el delete, borrar cualquier mascota ocasiona que se borre la mascota que figura con el _menor id_. 
Despues en el resto de cosas anda bien.

## CRUD de clientes
Funciona todo bien excepto lo del delete que, al borrar cualquier cliente, borra al de _menor id_.

---
Corregi esas cositas y estaría. Me parecería correcto si las cosas que mencionaste las elevamos como issue asi si las tenemos pendientes y se las podemos preguntar a algun profesor o algo

2024-07-14 22:10 UTC, JosepSoc commented
Ahi corregi lo de la imagen, si la imagen era mas chica que el form quedaba de costado y no probe con una imagen grande. Resto de cambios a otra branch

2024-07-14 22:28 UTC, mateoregodesebes approved these changes
LGTM. Los errores relacionados a la lógica del delete de los CRUD's quedan para otra branch

2024-07-14 22:29 UTC, merged