feature: register, login & logout
mateoregodesebes/Pagina-Veterinaria pull request #5
Opened 2024-02-11 22:47 UTC by mateoregodesebes

Ahí debería estar, el modal esta funcionando y todo anda. Tengo que arreglar la db del webhost para que tenga el campo contraseña también.

2024-02-12 21:20 UTC, JosepSoc commented on src/partials/navbar.php
> +                        <form class="px-4 py-3" action="index.php" method="POST">
Yo meteria un toque mas de espaciado por entre los label, input y boton, capaz 1px. Igual es sugerencia

2024-02-12 21:21 UTC, JosepSoc commented on src/pages/registration/registration.php
> +            <div class="form-btn">
El boton este de reset lo haria rojo

2024-02-12 21:32 UTC, JosepSoc requested changes
2-3 cositas que no se si es mi xampp pero on andan y alguna suggestion. Con arreglar el feedback cuando la contraseña es incorrecta y el pathing ese esta mergeable.

2024-02-12 21:32 UTC, JosepSoc commented on src/pages/registration/registration.php
> +        $_SESSION['currentPage'] = '..\src\pages\contact\contact.php';
Este pathing no me anduvo pero igual hay que cambiarlo por el home php, el usuario se crea y todo pero te tira el error de pathing a contact.php

2024-02-12 21:32 UTC, JosepSoc commented on src/scripts/login.php
> +                # Check if these echoes work
Este creo que no anda

2024-02-12 22:56 UTC, mateoregodesebes commented on src/pages/registration/registration.php
> +        $_SESSION['currentPage'] = '..\src\pages\contact\contact.php';
Me olvidé de cambiar los slashes invertidos (\) por los normales (/)

2024-02-12 23:04 UTC, mateoregodesebes commented
Ahi cambié el outline del boton de reset por el 'btn-outline-danger', fijate si te gusta. Con el tema del padding del login, le agregué un poquito más pero no me termina de convencer, no se que te parece.

2024-02-13 23:18 UTC, JosepSoc approved these changes
Quedo todo ok, hay algo raro calculo del styles del registration que hace que cuando abris el dropdown del login ahi se corre un poco los label y los input pero nada que no sea mergeable. A main nomas

2024-02-13 23:18 UTC, merged